### ISSUE TITLE
Ellipsoid grains

### ISSUE THREAD

**Issue by wID9527** [MosGeo/ParticlePack#13]
Hi
Thank you much for your package！
Are there ellipsoid grains that could be added in the box? I would like to know if it can be achieved by changing the parameter grain type.

**Comment by MosGeo** [comment]
Change the Scale parameter for the grain in the paramter file

Example:

**from:**
Bed 1 Grain 1 Scale = [1 1 1]
**to:**
Bed 1 Grain 1 Scale = [1 0.5 1]

**Comment by wID9527** [comment]
Thank you much for your reply! 
It succeed.

**Comment by MosGeo** [comment]
Great. I will close the issue.
