### ISSUE TITLE
Can the packing process be saved as a gif or movie?

### ISSUE THREAD

**Issue by rpshi** [MosGeo/ParticlePack#3]
Hi Mustafa:

Again, many thanks for sharing the great tool.

I am wondering if one can save the shaking /packing/pouring process as a movie when run the executable file?

It would be very cool!

R-P

**Comment by MosGeo** [comment]
To record, I usually just use the built in Windows 10 functionality in thr game bar. There is alot of info on it on the internet. It produces a movie file. The movie file can be converted to gif using a online converter or a desktop application if needed.

https://www.polygon.com/2015/7/31/9081715/windows-10-game-bar-how-to-record-screen-video

**Comment by rpshi** [comment]
Game bar works perfectly. Thanks!!
