### ISSUE TITLE
multiple beds can be simulated to produce geologically realistic grading??

### ISSUE THREAD

**Issue by rpshi** [MosGeo/ParticlePack#5]
Hi Mustafa:

Do you have an example about how to generate multiple beds ( the example on the right as shown in the figure below?)

or you just generated individual beds and stacked them together?

Thank you for your time!

Best regards,

Rongpei

https://github.com/MosGeo/ParticlePack/blob/master/ReadmeFiles/Grading.png

**Comment by MosGeo** [comment]
That is possible directly in the simulator. I will create a parameter file for an example with multiple beds. It is straight forward to understand.

**Comment by rpshi** [comment]
That would be fantastic. Thanks for your time and efforts.

Cheers,

Rongpei

**Comment by MosGeo** [comment]
Commit faf449e9e9d57e3769a757fb0c8df38a96b294a2 adds a six example with multiple beds (Example 6: complex)

https://github.com/MosGeo/ParticlePack/blob/master/Source/Assets/Parameters_06_Complex.txt

Note the use of numbering: Bed 1, Bed 1 Grain 1, Bed 2, Bed 2 Grain 1. Those are important.

Note: 
One bed defines grains that are deposited together. A bed can contain multiple grain types (in the example, i kept it to one type per bed for simplicity).
